---
# For training
path_src: 'datasets/images'
path_bg: 'datasets/layers/background'
path_regions: 'datasets/regions'
path_layer:
  - 'datasets/layers/staff'
  - 'datasets/layers/neumes'
path_out: 
  - 'Models/model_background.h5'
  - 'Models/model_staff.h5'
  - 'Models/model_neumes.h5'

# For evaluating
path_ckpt: # Load ckpts from here
  - 'Resources/MS73Ckpts_1000/MS73_train_BG_w256_n1000.h5'
  - 'Resources/MS73Ckpts_1000/MS73_train_staff_w256_n1000.h5'
  - 'Resources/MS73Ckpts_1000/MS73_train_neumes_w256_n1000.h5'
testset: # A list of test images
  - "Resources/MS73ClassifyTc/Image - 040.png"
  - "Resources/MS73ClassifyTc/Image - 068.png"

# Shared setting
patch_height: 256
patch_width: 256

number_samples_per_class: 1000
batch_size: 8
patience: 15
max_epochs: 50

sample_extraction_mode: "RANDOM"
file_selection_mode: "SHUFFLE"